/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-01 14:16:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch08;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class validation02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function checkMember() {\r\n");
      out.write("		var form = document.Member;\r\n");
      out.write("		var id = form.id.value;\r\n");
      out.write("		\r\n");
      out.write("		//대괄호'앞'에 ^가 붙으면 시작을 의미\r\n");
      out.write("		//대괄호'안'에 ^가 붙으면 제외를 의미\r\n");
      out.write("		var regExpId = /^[a-z|A-Z|ㄱ-ㅎ|가-힣]/;\r\n");
      out.write("		\r\n");
      out.write("		//+문자열 연결, $는 문자열종료, g는 문자열내의 모든 패턴을 검출\r\n");
      out.write("		//var regExpId = /^[a-z]+[a-z0-9]{5,19}$/g;\r\n");
      out.write("		\r\n");
      out.write("		//var regExpId = /^P[0-9]{4,11}$/;\r\n");
      out.write("		if(!regExpId.test(id)){\r\n");
      out.write("			alert(\"아이디는 문자로 시작해주세요\");\r\n");
      out.write("			form.id.select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var passwd = form.passwd.value;\r\n");
      out.write("		//*는 0회이상 연속적으로 반복\r\n");
      out.write("		var regExpPasswd = /^[0-9]*$/;\r\n");
      out.write("		if(!regExpPasswd.test(passwd)){\r\n");
      out.write("			alert(\"패스워드는 숫자로 시작하세요\");\r\n");
      out.write("			form.passwd.select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var name = form.name.value;\r\n");
      out.write("		var regExpName = /^[가-힣]*$/;\r\n");
      out.write("		if(!regExpName.test(name)){\r\n");
      out.write("			alert(\"이름은 한글만 입력하세요\");\r\n");
      out.write("			form.name.select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var phone = form.phone1.value + \"-\" + form.phone2.value + \"-\" + form.phone3.value;\r\n");
      out.write("		var regExpPhone = /^\\d{3}-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("		if(!regExpPhone.test(phone)){\r\n");
      out.write("			alert(\"전화번호를 다시 입력하세요\");\r\n");
      out.write("			form.phone.select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		form.submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<h3>회원가입</h3>\r\n");
      out.write("	<form name=\"Member\" action=\"validation02_process.jsp\" method=\"post\">\r\n");
      out.write("		<p>아이디 : <input type=\"text\" name=\"id\"><input type=\"button\" value=\"아이디중복검사\">\r\n");
      out.write("		<p>비밀번호 : <input type=\"password\" name=\"passwd\">\r\n");
      out.write("		<p>이름 : <input type=\"text\" name=\"name\">\r\n");
      out.write("		<p>연락처 : <select name=\"phone1\">\r\n");
      out.write("						<option value=\"010\">010\r\n");
      out.write("						<option value=\"016\">016\r\n");
      out.write("						<option value=\"017\">017\r\n");
      out.write("						<option value=\"018\">018\r\n");
      out.write("				   </select>-<input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone2\">-\r\n");
      out.write("				   			 <input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone3\">\r\n");
      out.write("		<p>이메일 : <input type=\"email\" name=\"email\">\r\n");
      out.write("		<p><input type=\"button\" value=\"가입하기\" onclick=\"checkMember()\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
